### ISSUE TITLE
[ec] do research about quartz

### ISSUE THREAD

**Issue by Alice52** [Alice52/project#119]

**Comment by Alice52** [comment]
## cron expression

![image](https://user-images.githubusercontent.com/42330329/102888608-18643100-4494-11eb-8728-db7badb8112d.png)

**Comment by Alice52** [comment]
## Recommend

```json 
{// Recommend to use addJob(xx) to schedule, and specified JobDetail when build trigger, then scheduleJob by trigger}
````

**Comment by Alice52** [comment]
## 2. durable

1. config: `main database or self database`

    ```yaml
    quartz:
      datasource:
        url: ENC(xx)
        username: ENC(xt)
        password: ENC(x)
        driverClassName: com.mysql.cj.jdbc.Driver
    
    spring:
      quartz:
        job-store-type: jdbc
        jdbc:
          # when config initialize-schema: always, it will drop tables and re-create when server start-up
          initialize-schema: never
          comment-prefix: '#'
        properties:
          org.quartz.scheduler.instanceId: AUTO
          org.quartz.threadPool.threadCount: 500
    ```

    ```sql
    select TABLE_SCHEMA, TABLE_NAME, TABLE_ROWS from information_schema.`TABLES` where TABLE_SCHEMA = 'quartz' and TABLE_NAME like '%QRTZ%';
    SELECT * from QRTZ_SCHEDULER_STATE;
    ````

2. if quarzt is `not run as cluster mode`, recommend to set ` initialize-schema: always`
3. if quartz run as cluster mode, donnot allow to delete tables, so recommend use api to trigger relations of job-detail andtriggers. ~~`scheduler.scheduleJob(jobDetail, Sets.newHashSet(trigger), true);` is also ok, but not recommend~~

**Comment by Alice52** [comment]
## quartz cluster

1. requirement

   - **`must be based on jdbc store.`**

2. config

   ```yaml
   server:
     port: 8081
   quartz:
     datasource:
       url: ENC(xxx)
       username: ENC(xx)
       password: ENC(xx)
       driverClassName: com.mysql.cj.jdbc.Driver
   spring:
     profiles:
       include: common
     application:
       name: boot-job-quartz-2
     quartz:
       job-store-type: jdbc
       jdbc:
         # when config initialize-schema: always, it will drop tables and re-create when server start-up
         initialize-schema: always
         comment-prefix: '#'
       properties:
         org.quartz.jobStore.isClustered: true
         org.quartz.scheduler.instanceId: SERVICE-2
         org.quartz.scheduler.instanceName: ${spring.application.name}
   ```

3. start-up server with job-init to create table in database.

   ```java
   @Component
   public class ClusterJobInit {
     private static final Logger LOG = LoggerFactory.getLogger(ClusterJobInit.class);
     @Resource Scheduler scheduler;

     @PostConstruct
     public void initJob() throws SchedulerException {
       final int poolSize = scheduler.getMetaData().getThreadPoolSize();
       LOG.info("quartz thread count in cluster job config: {}", poolSize);

       startJob("cluster-job-1", "cluster-trigger-1");
       startJob("cluster-job-2", "cluster-trigger-2");
       startJob("cluster-job-3", "cluster-trigger-3");
     }

     /**
     * Recommend to use api to trigger relation between job-detail and triggers.
     *
     * @param jobName
     * @param triggerName
     * @throws SchedulerException
     */
     @Deprecated
     private void startJob(String jobName, String triggerName) throws SchedulerException {
       JobDetail jobDetail =
           JobBuilder.newJob(SimpleJob.class).withIdentity(jobName).storeDurably(true).build();
       Trigger trigger =
           TriggerBuilder.newTrigger()
               .withIdentity(triggerName)
               .withSchedule(
                   SimpleScheduleBuilder.simpleSchedule().withIntervalInSeconds(5).repeatForever())
               .startNow()
               .build();
       scheduler.scheduleJob(jobDetail, Sets.newHashSet(trigger), true);
     }
   }
   ```

4. change `initialize-schema: always` to `initialize-schema: never`

   - all cluster instance cannot be allowed to delete quartz tables
   - if each instance start-up re-create tables, it will has side impact on others instance
   - then execute time will be massed

5. run/start-up all instances
